# Generated by Django 5.1.6 on 2025-02-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.BinaryField()),
                ('refresh', models.BinaryField(default=b'auroraworld')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('category', models.CharField(choices=[('favorites', '개인즐겨찾기'), ('work', '업무 활용자료'), ('reference', '참고자료'), ('education', '교육 및 학습자료')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='database.user')),
            ],
            options={
                'db_table': 'weblinks',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='database.user')),
                ('shared_by_weblink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_shares', to='database.weblink')),
            ],
            options={
                'db_table': 'shares',
                'unique_together': {('shared_with_user', 'shared_by_weblink')},
            },
        ),
    ]
